print("An artificial, golden planet, made of interlocking orbs,")
print("revolves around a blue sun.")
print("We PUSH IN on THUNDEROUS INTERDIMENSIONAL CRACKS on one small")
print("patch of planet.")
print("SUPER: THE SOVEREIGN")
print("M49 5IOL339P21+H9LNI31")
print("I/E. POWER STATION - DAY")
print("A DIMENSIONAL CRACK SNAPS in the sky overhead. PETER QUILL")
print("looks from it to an old MATTEL ELECTRONICS FOOTBALL GAME")
print("converted into a tracker. A RED DOT APPROACHES.")
print("QUILL")
print("Showtime, a-holes! It’ll be here")
print("any minute")
print("GAMORA")
print("Which will be its loss.")
print("Quill turns toward GAMORA, loading a rifle. DRAX, ROCKET,")
print("and BABY GROOT also ready themselves for battle in this")
print("grand, open-air power station. Dozens of BATTERIES are")
print("couched in conductor towers encircling them. Quill, Gamora,")
print("and Rocket wear flying rigs.")
print("QUILL")
print("Is that a rifle?")
print("GAMORA")
print("You don’t know what a rifle is?")
print("QUILL")
print("I thought your thing was a sword.")
print("GAMORA")
print("We’ve been hired to stop an")
print("interdimensional beast from feeding")
print("on those batteries’ energy, and I’m")
print("going to stop it with a sword?")
print("QUILL")
print("mumbling to himself")
print("Don’t look at me like I’m stupid.")
print("You’re the one being all")
print("inconsistent.")
print("A LOUDER, LARGER CRACK: something seems to be fighting its")
print("way through the sky.")
